[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_FIREBASE_API_KEY = "placeholder"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "placeholder"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "placeholder"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "placeholder"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "placeholder"
  NEXT_PUBLIC_FIREBASE_APP_ID = "placeholder"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "placeholder"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
